-------------------------------------------------------
-- Author: Jakub Miženko (xmizenj00)
-- Author: Marc Bafalluy Gesti (xbafalm00)



----------- DROP TABLES -----------

DROP TABLE registration CASCADE CONSTRAINTS;
DROP TABLE match_event CASCADE CONSTRAINTS;
DROP TABLE training CASCADE CONSTRAINTS;
DROP TABLE coach CASCADE CONSTRAINTS;
DROP TABLE player CASCADE CONSTRAINTS;
DROP TABLE stadium CASCADE CONSTRAINTS;
DROP TABLE team CASCADE CONSTRAINTS;
DROP TABLE person CASCADE CONSTRAINTS;

----------- CREATE TABLES -----------

-- birth_number was added to PERSON as a unique identifier with specific format
CREATE TABLE person (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(60) NOT NULL,
    address VARCHAR2(120) NOT NULL,
    age NUMBER(3) NOT NULL,
    birth_number VARCHAR2(11) NOT NULL UNIQUE,
    CONSTRAINT chk_person_age CHECK (age BETWEEN 5 AND 100),
    CONSTRAINT chk_person_birth_number CHECK (
        REGEXP_LIKE(birth_number, '^[0-9]{6}/?[0-9]{4}$')
    )
);


CREATE TABLE team (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    category VARCHAR2(30) NOT NULL,
    name VARCHAR2(80) NOT NULL UNIQUE,
    player_count NUMBER(3) DEFAULT 0 NOT NULL,
    coach_count NUMBER(3) DEFAULT 0 NOT NULL,
    CONSTRAINT chk_team_counts CHECK (player_count >= 0 AND coach_count >= 0)
);


CREATE TABLE stadium (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    stadium_type VARCHAR2(30) NOT NULL,
    ownership VARCHAR2(30) NOT NULL,
    name VARCHAR2(80) NOT NULL,
    address VARCHAR2(120) NOT NULL,
    spectator_capacity NUMBER(6) NOT NULL,
    player_capacity NUMBER(4) NOT NULL,
    CONSTRAINT chk_stadium_ownership CHECK (ownership IN ('OWNED', 'RENTED')),
    CONSTRAINT chk_stadium_capacity CHECK (spectator_capacity >= 0 AND player_capacity > 0)
);



-- Generalization/Specialization:
-- PERSON is supertype, PLAYER and COACH are subtypes
-- Relations: subtype PK is also FK to PERSON.ID
CREATE TABLE player (
    id NUMBER PRIMARY KEY,
    team_id NUMBER NOT NULL,
    height_cm NUMBER(3) NOT NULL,
    weight_kg NUMBER(3) NOT NULL,
    position_name VARCHAR2(30) NOT NULL,
    jersey_number NUMBER(2) NOT NULL,
    CONSTRAINT fk_player_person FOREIGN KEY (id) REFERENCES person(id),
    CONSTRAINT fk_player_team FOREIGN KEY (team_id) REFERENCES team(id),
    CONSTRAINT chk_player_height CHECK (height_cm BETWEEN 120 AND 250),
    CONSTRAINT chk_player_weight CHECK (weight_kg BETWEEN 35 AND 200),
    CONSTRAINT chk_player_jersey CHECK (jersey_number BETWEEN 1 AND 99),
    CONSTRAINT uq_player_team_jersey UNIQUE (team_id, jersey_number)
);

CREATE TABLE coach (
    id NUMBER PRIMARY KEY,
    team_id NUMBER NOT NULL,
    role_name VARCHAR2(30) NOT NULL,
    CONSTRAINT fk_coach_person FOREIGN KEY (id) REFERENCES person(id),
    CONSTRAINT fk_coach_team FOREIGN KEY (team_id) REFERENCES team(id)
);


CREATE TABLE training (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    team_id NUMBER NOT NULL,
    stadium_id NUMBER NOT NULL,
    coach_id NUMBER NOT NULL,
    training_type VARCHAR2(10) NOT NULL,
    training_date DATE NOT NULL,
    training_time VARCHAR2(5) NOT NULL,
    auto_registration CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT fk_training_team FOREIGN KEY (team_id) REFERENCES team(id),
    CONSTRAINT fk_training_stadium FOREIGN KEY (stadium_id) REFERENCES stadium(id),
    CONSTRAINT fk_training_coach FOREIGN KEY (coach_id) REFERENCES coach(id),
    CONSTRAINT chk_training_type CHECK (training_type IN ('REGULAR', 'ONE_TIME')),
    CONSTRAINT chk_training_time CHECK (REGEXP_LIKE(training_time, '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$')),
    CONSTRAINT chk_training_auto CHECK (auto_registration IN ('Y', 'N'))
);


CREATE TABLE match_event (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    team_id NUMBER NOT NULL,
    stadium_id NUMBER,
    away_address VARCHAR2(150),
    home_away CHAR(1) NOT NULL,
    opponent_name VARCHAR2(80) NOT NULL,
    match_date DATE NOT NULL,
    match_time VARCHAR2(5) NOT NULL,
    roster_capacity NUMBER(3) NOT NULL,
    result_text VARCHAR2(20),
    CONSTRAINT fk_match_team FOREIGN KEY (team_id) REFERENCES team(id),
    CONSTRAINT fk_match_stadium FOREIGN KEY (stadium_id) REFERENCES stadium(id),
    CONSTRAINT chk_match_home_away CHECK (home_away IN ('H', 'A')),
    CONSTRAINT chk_match_time CHECK (REGEXP_LIKE(match_time, '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$')),
    CONSTRAINT chk_match_roster CHECK (roster_capacity > 0),
    CONSTRAINT chk_match_place CHECK (
        (home_away = 'H' AND stadium_id IS NOT NULL AND away_address IS NULL) OR
        (home_away = 'A' AND stadium_id IS NULL AND away_address IS NOT NULL)
    )
);


CREATE TABLE registration (
    id NUMBER PRIMARY KEY,
    status_name VARCHAR2(20) NOT NULL,
    event_type VARCHAR2(10) NOT NULL,
    player_id NUMBER NOT NULL,
    match_id  NUMBER,
    training_id NUMBER,
    created_by_player_id NUMBER,
    created_by_coach_id NUMBER,
    CONSTRAINT fk_registration_player FOREIGN KEY (player_id) REFERENCES player(id),
    CONSTRAINT fk_registration_match FOREIGN KEY (match_id) REFERENCES match_event(id),
    CONSTRAINT fk_registration_training FOREIGN KEY (training_id) REFERENCES training(id),
    CONSTRAINT fk_registration_created_player FOREIGN KEY (created_by_player_id) REFERENCES player(id),
    CONSTRAINT fk_registration_created_coach FOREIGN KEY (created_by_coach_id) REFERENCES coach(id),
    CONSTRAINT chk_registration_status CHECK (status_name IN ('REGISTERED', 'CANCELLED', 'WAITING')),
    CONSTRAINT chk_registration_event_type CHECK (event_type IN ('MATCH', 'TRAINING')),
    -- exactly one event target
    CONSTRAINT chk_registration_event CHECK (
        (match_id IS NOT NULL AND training_id IS NULL) OR
        (match_id IS NULL AND training_id IS NOT NULL)
    ),
    -- event_type must match selected event
    CONSTRAINT chk_registration_event_consistency CHECK (
        (event_type = 'MATCH' AND match_id IS NOT NULL AND training_id IS NULL) OR
        (event_type = 'TRAINING' AND training_id IS NOT NULL AND match_id IS NULL)
    ),
    -- exactly one author
    CONSTRAINT chk_registration_author CHECK (
        (created_by_player_id IS NOT NULL AND created_by_coach_id IS NULL) OR
        (created_by_player_id IS NULL AND created_by_coach_id IS NOT NULL)
    ),
    -- if created by player, it must be self-registration
    CONSTRAINT chk_registration_self_player CHECK (
        created_by_player_id IS NULL OR created_by_player_id = player_id
    ),
    -- match registration must be done by coach (not by player)
    CONSTRAINT chk_registration_match_author CHECK (
        (event_type = 'MATCH' AND created_by_coach_id IS NOT NULL AND created_by_player_id IS NULL) OR
        (event_type = 'TRAINING')
    )
);
---   TODO:
---       id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY
---       this should work too, but i don't know if it is correct to use, we need to ask someone,
---       now we have both sequence/trigger and indentity

----------- SEQUENCE AND TRIGGER FOR REGISTRATION ID WHEN NULL -----------
CREATE SEQUENCE seq_registration_id
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER trg_registration_id
BEFORE INSERT ON registration
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT seq_registration_id.NEXTVAL INTO :NEW.id FROM dual;
    END IF;
END;
/


----------- INSERT -----------

-- Team
INSERT INTO team (category, name, player_count, coach_count)
VALUES ('MEN', 'FC Wolves', 2, 1);
INSERT INTO team (category, name, player_count, coach_count)
VALUES ('JUNIORS', 'FC Wolves Juniors', 0, 0);

-- Stadium
INSERT INTO stadium (stadium_type, ownership, name, address, spectator_capacity, player_capacity)
VALUES ('PITCH', 'OWNED', 'Main Stadium', 'Main 1, Brno', 15000, 30);
INSERT INTO stadium (stadium_type, ownership, name, address, spectator_capacity, player_capacity)
VALUES ('GYM', 'RENTED', 'City Gym', 'Sport 55, Brno', 200, 25);

-- Person
INSERT INTO person (full_name, address, age, birth_number)
VALUES ('Adam Player', 'Street 10, Brno', 23, '010101/1234');
INSERT INTO person (full_name, address, age, birth_number)
VALUES ('Boris Player', 'Street 20, Brno', 21, '020202/2345');
INSERT INTO person (full_name, address, age, birth_number)
VALUES ('Karel Coach', 'Street 30, Brno', 45, '800101/3456');

-- Player
INSERT INTO player (id, team_id, height_cm, weight_kg, position_name, jersey_number)
SELECT p.id, t.id, 182, 76, 'FORWARD', 9
FROM person p
JOIN team t ON t.name = 'FC Wolves'
WHERE p.birth_number = '010101/1234';

INSERT INTO player (id, team_id, height_cm, weight_kg, position_name, jersey_number)
SELECT p.id, t.id, 178, 72, 'MIDFIELDER', 8
FROM person p
JOIN team t ON t.name = 'FC Wolves'
WHERE p.birth_number = '020202/2345';

-- Coach
INSERT INTO coach (id, team_id, role_name)
SELECT p.id, t.id, 'HEAD_COACH'
FROM person p
JOIN team t ON t.name = 'FC Wolves'
WHERE p.birth_number = '800101/3456';

-- Training
INSERT INTO training (team_id, stadium_id, coach_id, training_type, training_date, training_time, auto_registration)
SELECT t.id, s.id, c.id, 'REGULAR', DATE '2026-04-15', '17:00', 'Y'
FROM team t
JOIN stadium s ON s.name = 'Main Stadium'
JOIN person p ON p.birth_number = '800101/3456'
JOIN coach c ON c.id = p.id
WHERE t.name = 'FC Wolves';

-- Home match
INSERT INTO match_event (team_id, stadium_id, away_address, home_away, opponent_name, match_date, match_time, roster_capacity, result_text)
SELECT t.id, s.id, NULL, 'H', 'FC Rivals', DATE '2026-04-20', '18:00', 18, '2:1'
FROM team t
JOIN stadium s ON s.name = 'Main Stadium'
WHERE t.name = 'FC Wolves';

-- Away match
INSERT INTO match_event (team_id, stadium_id, away_address, home_away, opponent_name, match_date, match_time, roster_capacity, result_text)
SELECT t.id, NULL, 'Away Stadium 99, Praha', 'A', 'FC Sparta B', DATE '2026-04-27', '19:00', 18, NULL
FROM team t
WHERE t.name = 'FC Wolves';

-- Player self-registration to training
INSERT INTO registration (status_name, event_type, player_id, training_id, created_by_player_id)
SELECT 'REGISTERED', 'TRAINING', pl.id, tr.id, pl.id
FROM player pl
JOIN person pp ON pp.id = pl.id
JOIN training tr ON tr.training_date = DATE '2026-04-15' AND tr.training_time = '17:00'
WHERE pp.birth_number = '010101/1234';

-- Coach registers player to match
INSERT INTO registration (status_name, event_type, player_id, match_id, created_by_coach_id)
SELECT 'REGISTERED', 'MATCH', pl.id, me.id, c.id
FROM player pl
JOIN person p_pl ON p_pl.id = pl.id
JOIN match_event me ON me.match_date = DATE '2026-04-20' AND me.match_time = '18:00' AND me.opponent_name = 'FC Rivals'
JOIN person p_c ON p_c.birth_number = '800101/3456'
JOIN coach c ON c.id = p_c.id
WHERE p_pl.birth_number = '020202/2345';

COMMIT;