-------------------------------------------------------
-- Author: Jakub Miženko (xmizenj00)
-- Author: Marc Bafalluy Gesti (xbafalm00)


----------- DROP TABLES -----------

DROP TABLE registration CASCADE CONSTRAINTS;
DROP TABLE match_event CASCADE CONSTRAINTS;
DROP TABLE training CASCADE CONSTRAINTS;
DROP TABLE coach CASCADE CONSTRAINTS;
DROP TABLE player CASCADE CONSTRAINTS;
DROP TABLE stadium CASCADE CONSTRAINTS;
DROP TABLE team CASCADE CONSTRAINTS;
DROP TABLE person CASCADE CONSTRAINTS;


----------- CREATE TABLES -----------

-- birth_number was added to PERSON as a unique identifier with specific format
CREATE TABLE person (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(60) NOT NULL,
    address VARCHAR2(120) NOT NULL,
    age NUMBER(3) NOT NULL,
    birth_number VARCHAR2(11) NOT NULL UNIQUE,
    CONSTRAINT chk_person_age CHECK (age BETWEEN 5 AND 100),
    CONSTRAINT chk_person_birth_number CHECK (
        REGEXP_LIKE(birth_number, '^[0-9]{6}/?[0-9]{4}$')
    )
);


CREATE TABLE team (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    category VARCHAR2(30) NOT NULL,
    name VARCHAR2(80) NOT NULL UNIQUE,
    player_count NUMBER(3) DEFAULT 0 NOT NULL,
    coach_count NUMBER(3) DEFAULT 0 NOT NULL,
    CONSTRAINT chk_team_counts CHECK (player_count >= 0 AND coach_count >= 0)
);


CREATE TABLE stadium (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    stadium_type VARCHAR2(30) NOT NULL,
    ownership VARCHAR2(30) NOT NULL,
    name VARCHAR2(80) NOT NULL,
    address VARCHAR2(120) NOT NULL,
    spectator_capacity NUMBER(6) NOT NULL,
    player_capacity NUMBER(4) NOT NULL,
    CONSTRAINT chk_stadium_ownership CHECK (ownership IN ('OWNED', 'RENTED')),
    CONSTRAINT chk_stadium_capacity CHECK (spectator_capacity >= 0 AND player_capacity > 0)
);


-- Generalization/Specialization:
-- PERSON is supertype, PLAYER and COACH are subtypes
-- Relations: subtype PK is also FK to PERSON.ID
CREATE TABLE player (
    id NUMBER PRIMARY KEY,
    team_id NUMBER NOT NULL,
    height_cm NUMBER(3) NOT NULL,
    weight_kg NUMBER(3) NOT NULL,
    position_name VARCHAR2(30) NOT NULL,
    jersey_number NUMBER(2) NOT NULL,
    CONSTRAINT fk_player_person FOREIGN KEY (id) REFERENCES person(id),
    CONSTRAINT fk_player_team FOREIGN KEY (team_id) REFERENCES team(id),
    CONSTRAINT chk_player_jersey CHECK (jersey_number BETWEEN 1 AND 99),
    CONSTRAINT uq_player_team_jersey UNIQUE (team_id, jersey_number)
);

CREATE TABLE coach (
    id NUMBER PRIMARY KEY,
    team_id NUMBER NOT NULL,
    role_name VARCHAR2(30) NOT NULL,
    CONSTRAINT fk_coach_person FOREIGN KEY (id) REFERENCES person(id),
    CONSTRAINT fk_coach_team FOREIGN KEY (team_id) REFERENCES team(id)
);


CREATE TABLE training (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    team_id NUMBER NOT NULL,
    stadium_id NUMBER NOT NULL,
    coach_id NUMBER NOT NULL,
    training_type VARCHAR2(10) NOT NULL,
    training_date DATE NOT NULL,
    training_time VARCHAR2(5) NOT NULL,
    auto_registration CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT fk_training_team FOREIGN KEY (team_id) REFERENCES team(id),
    CONSTRAINT fk_training_stadium FOREIGN KEY (stadium_id) REFERENCES stadium(id),
    CONSTRAINT fk_training_coach FOREIGN KEY (coach_id) REFERENCES coach(id),
    CONSTRAINT chk_training_type CHECK (training_type IN ('REGULAR', 'ONE_TIME')),
    CONSTRAINT chk_training_time CHECK (REGEXP_LIKE(training_time, '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$')),
    CONSTRAINT chk_training_auto CHECK (auto_registration IN ('Y', 'N'))
);


CREATE TABLE match_event (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    team_id NUMBER NOT NULL,
    stadium_id NUMBER,
    away_address VARCHAR2(150),
    home_away CHAR(1) NOT NULL,
    opponent_name VARCHAR2(80) NOT NULL,
    match_date DATE NOT NULL,
    match_time VARCHAR2(5) NOT NULL,
    roster_capacity NUMBER(3) NOT NULL,
    match_result VARCHAR2(20),
    CONSTRAINT fk_match_team FOREIGN KEY (team_id) REFERENCES team(id),
    CONSTRAINT fk_match_stadium FOREIGN KEY (stadium_id) REFERENCES stadium(id),
    CONSTRAINT chk_match_home_away CHECK (home_away IN ('H', 'A')),
    CONSTRAINT chk_match_time CHECK (REGEXP_LIKE(match_time, '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$')),
    CONSTRAINT chk_match_roster CHECK (roster_capacity > 0),
    CONSTRAINT chk_match_place CHECK (
        (home_away = 'H' AND stadium_id IS NOT NULL AND away_address IS NULL) OR
        (home_away = 'A' AND stadium_id IS NULL AND away_address IS NOT NULL)
    )
);


CREATE TABLE registration (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    status_name VARCHAR2(20) NOT NULL,
    event_type VARCHAR2(10) NOT NULL,
    player_id NUMBER NOT NULL,
    match_id  NUMBER,
    training_id NUMBER,
    created_by_player_id NUMBER,
    created_by_coach_id NUMBER,
    CONSTRAINT fk_registration_player FOREIGN KEY (player_id) REFERENCES player(id),
    CONSTRAINT fk_registration_match FOREIGN KEY (match_id) REFERENCES match_event(id),
    CONSTRAINT fk_registration_training FOREIGN KEY (training_id) REFERENCES training(id),
    CONSTRAINT fk_registration_created_player FOREIGN KEY (created_by_player_id) REFERENCES player(id),
    CONSTRAINT fk_registration_created_coach FOREIGN KEY (created_by_coach_id) REFERENCES coach(id),
    CONSTRAINT chk_registration_status CHECK (status_name IN ('REGISTERED', 'CANCELLED', 'WAITING')),
    CONSTRAINT chk_registration_event_type CHECK (event_type IN ('MATCH', 'TRAINING')),
    CONSTRAINT chk_registration_event CHECK (
        (match_id IS NOT NULL AND training_id IS NULL) OR
        (match_id IS NULL AND training_id IS NOT NULL)
    ),
    CONSTRAINT chk_registration_event_consistency CHECK (
        (event_type = 'MATCH' AND match_id IS NOT NULL AND training_id IS NULL) OR
        (event_type = 'TRAINING' AND training_id IS NOT NULL AND match_id IS NULL)
    ),
    CONSTRAINT chk_registration_author CHECK (
        (created_by_player_id IS NOT NULL AND created_by_coach_id IS NULL) OR
        (created_by_player_id IS NULL AND created_by_coach_id IS NOT NULL)
    ),
    CONSTRAINT chk_registration_self_player CHECK (
        created_by_player_id IS NULL OR created_by_player_id = player_id
    ),
    CONSTRAINT chk_registration_match_author CHECK (
        (event_type = 'MATCH' AND created_by_coach_id IS NOT NULL AND created_by_player_id IS NULL) OR
        (event_type = 'TRAINING')
    )
);


----------- INSERT -----------

-- Team
INSERT INTO team (id, category, name, player_count, coach_count)
VALUES (1, 'MEN', 'FC Barcelona', 2, 1);
INSERT INTO team (id, category, name, player_count, coach_count)
VALUES (2, 'JUNIORS', 'FC Barcelona Juniors', 0, 0);

-- Stadium
INSERT INTO stadium (id, stadium_type, ownership, name, address, spectator_capacity, player_capacity)
VALUES (1, 'PITCH', 'OWNED', 'Main Stadium', 'Main 1, Brno', 15000, 30);
INSERT INTO stadium (id, stadium_type, ownership, name, address, spectator_capacity, player_capacity)
VALUES (2, 'GYM', 'RENTED', 'City Gym', 'Sport 55, Brno', 200, 25);
-- Person

INSERT INTO person (id, full_name, address, age, birth_number)
VALUES (1, 'Adam Player', 'Street 10, Brno', 23, '010101/1234');
INSERT INTO person (id, full_name, address, age, birth_number)
VALUES (2, 'Boris Player', 'Street 20, Brno', 21, '020202/2345');
INSERT INTO person (id, full_name, address, age, birth_number)
VALUES (3, 'Karel Coach', 'Street 30, Brno', 45, '800101/3456');

-- Player
INSERT INTO player (id, team_id, height_cm, weight_kg, position_name, jersey_number)
VALUES (1, 1, 182, 76, 'FORWARD', 9);
INSERT INTO player (id, team_id, height_cm, weight_kg, position_name, jersey_number)
VALUES (2, 1, 178, 72, 'MIDFIELDER', 8);

-- Coach
INSERT INTO coach (id, team_id, role_name)
VALUES (3, 1, 'HEAD_COACH');

-- Training
INSERT INTO training (id, team_id, stadium_id, coach_id, training_type, training_date, training_time, auto_registration)
VALUES (1, 1, 1, 3, 'REGULAR', DATE '2026-04-25', '17:00', 'Y');

-- Match (HOME)
INSERT INTO match_event (id, team_id, stadium_id, away_address, home_away, opponent_name, match_date, match_time, roster_capacity, match_result)
VALUES (1, 1, 1, NULL, 'H', 'Newcastle United FC', DATE '2026-04-20', '18:00', 18, '2:1');

-- Match (AWAY)
INSERT INTO match_event (id, team_id, stadium_id, away_address, home_away, opponent_name, match_date, match_time, roster_capacity, match_result)
VALUES (2, 1, NULL, 'Away Stadium 99, Praha', 'A', 'Real Madrid', DATE '2026-04-27', '19:00', 18, NULL);

-- Registration: player self-registration to training
INSERT INTO registration (status_name, event_type, player_id, training_id, created_by_player_id)
VALUES ('REGISTERED', 'TRAINING', 1, 1, 1);

-- Registration: coach registers player to match
INSERT INTO registration (status_name, event_type, player_id, match_id, created_by_coach_id)
VALUES ('REGISTERED', 'MATCH', 2, 1, 3);

COMMIT;


----------- SELECT -----------

-- 1. List jersey numbers with their team name
-- Used in the app to display which position belongs to each jersey number
-- join of two tables --
SELECT pl.jersey_number, pl.position_name, t.name AS team_name
FROM player pl
JOIN team t ON pl.team_id = t.id
ORDER BY t.name, pl.jersey_number;

-- 2. List upcoming trainings with the stadium where they take place
-- Used in the app to show future training schedule with venue details
-- join of two tables --
SELECT tr.training_date, tr.training_time, tr.training_type, s.name AS stadium_name, s.address
FROM training tr
JOIN stadium s ON tr.stadium_id = s.id
WHERE tr.training_date >= SYSDATE
ORDER BY tr.training_date, tr.training_time;

-- 3. List players with their weight sorted from heaviest to lightest
-- Used in the app to display player weight statistics
-- join of two tables --
SELECT p.full_name, pl.weight_kg
FROM person p
JOIN player pl ON p.id = pl.id
ORDER BY pl.weight_kg DESC;

-- 4. List full player names with the team they play for
-- Used in the app to display the complete player profile with team assignment
-- join of three tables --
SELECT p.full_name, t.name AS team_name
FROM person p
JOIN player pl ON p.id = pl.id
JOIN team t ON pl.team_id = t.id
ORDER BY t.name, p.full_name;

-- 5. Tallest player height per team
-- Used in the app to show the tallest player in each team
-- GROUP BY with aggregate function MAX --
SELECT t.name AS team, MAX(pl.height_cm) AS tallest_player_height
FROM team t
JOIN player pl ON t.id = pl.team_id
GROUP BY t.name
ORDER BY t.name;

-- 6. Average age of players per team
-- Used in the app to show the average player age in each team
-- GROUP BY with aggregate function AVG --
SELECT t.name AS team, AVG(p.age) AS average_player_age
FROM team t
JOIN player pl ON t.id = pl.team_id
JOIN person p ON pl.id = p.id
GROUP BY t.name
ORDER BY t.name;

-- 7. Number of upcoming matches per team
-- Used in the app to show how many future matches each team has scheduled
-- GROUP BY with aggregate function COUNT --
SELECT t.name AS team, COUNT(m.id) AS match_count
FROM team t
JOIN match_event m ON t.id = m.team_id
WHERE m.match_date >= SYSDATE
GROUP BY t.name
ORDER BY t.name;

-- 8. List all people who are coaches
-- Used in the app to display the list of coaches from the person table
-- predicate EXISTS --
SELECT p.full_name AS coaches
FROM person p
WHERE EXISTS (
    SELECT *
    FROM coach c
    WHERE c.id = p.id
)
ORDER BY p.full_name;

-- 9. List all players who are registered for at least one upcoming training
-- Used in the app to show which players attend future trainings
-- predicate IN with nested SELECT --
SELECT p.full_name AS players_with_trainings
FROM person p
WHERE p.id IN (
    SELECT pl.id
    FROM player pl
    JOIN registration r ON pl.id = r.player_id
    JOIN training tr ON r.training_id = tr.id
    WHERE r.event_type = 'TRAINING'
    AND tr.training_date >= SYSDATE
)
ORDER BY p.full_name;